version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - palette-network
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - service-1
  service-1:
    image: repercussive/palette-generator-front
    build: service-1-front-end
    deploy:
      replicas: 3
    networks:
      - palette-network
  service-2:
    image: repercussive/palette-generator-base-color-api
    build: service-2-base-color-api
    deploy:
      replicas: 3
    networks:
      - palette-network
  service-3:
    image: repercussive/palette-generator-palette-type-api
    build: service-3-palette-type-api
    deploy:
      replicas: 3
    networks:
      - palette-network
  service-4:
    image: repercussive/palette-generator-create-palette-api
    build: service-4-create-palette-api
    container_name: service-4
    deploy:
      replicas: 3
    networks:
      - palette-network
networks:
  palette-network: